"""Ensure month_year column exists

Revision ID: 77b61358c99e
Revises: a3eccd5e33df
Create Date: 2025-01-20 16:12:44.976666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b61358c99e'
down_revision = 'a3eccd5e33df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense_category')
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month_year', sa.String(length=7), nullable=False))
        batch_op.drop_column('month')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_column('month_year')

    op.create_table('expense_category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='expense_category_pkey')
    )
    # ### end Alembic commands ###
