name: Deploy to EC2

on:
  push:
    branches:
      - '**'  # Or the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          cd /path/to/your/app
          git pull origin main
          source /path/to/your/virtualenv/bin/activate  # Activate virtual environment if needed
          pip install -r requirements.txt  # Install dependencies if needed
          sudo systemctl restart gunicorn  # Restart Gunicorn
          sudo systemctl reload nginx  # Reload Nginx to apply changes
        EOF